export enum EEndpointKeys {
  // Auth
  PostUserExistence = 'user-existence',
  PostCheckOTP = 'check-otp',
  GetCheckLogin = 'check-login',
  // Google
  GetGoogle = '',
  GetGoogleRedirect = 'redirect',
  // User
  GetFind = '',
  GetProfile = 'profile',
  GetFollow = 'follow/:followingId',
  GetFollowers = 'followers',
  GetFollowings = 'followings',
  GetRoles = 'roles',
  PostVerifyEmail = 'verify-email-otp',
  PostVerifyPhone = 'verify-phone',
  PostToggleBlock = 'toggle-block',
  UpdateProfile = '',
  PatchAddRoleToUser = 'add-role-to-user',
  PatchRemoveRoleFromUser = 'remove-role-from-user',
  PatchChangeEmail = 'change-email',
  PatchChangePhone = 'change-phone',
  PatchChangeUsername = 'change-username',
  // Category
  PostCreateCategory = '',
  GetFindAllCategories = '',
  GetFindOneCategory = ':id',
  PatchUpdateCategory = ':id',
  DeleteRemoveCategory = ':id',
  // Blog
  PostCreateBlog = '',
  GetMyBlogs = 'my-blogs',
  GetBlogs = '',
  GetBlogByID = 'by-id/:id',
  GetBlogBySlug = 'by-slug/:slug',
  DeleteBlog = ':id',
  PutUpdateBlog = ':id',
  GetToggleLike = 'like/:id',
  GetToggleBookmark = 'bookmark/:id',
  // Comment
  PostCreateComment = '',
  GetFindComments = '',
  GetFindMyComments = 'my-comments',
  PatchAcceptComment = 'accept/:id',
  PatchRejectComment = 'reject/:id',
}
